# Generated by Django 3.2.7 on 2021-09-24 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_photomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
