# Generated by Django 3.2.7 on 2021-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_photomodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='title'),
        ),
    ]
